services:
  ngextgencrackme:
    image: cybersecnatlab/challenge-jail@sha256:245f0de5bf5f9e9030dca9d9450672eea8d39474ea78a7902b93dff60f9060ad
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './ngc:/home/user/chall:ro'
      - './libs:/home/user/libs:ro'
    ports:
      - '47018:1337'
    environment:
      - 'FLAG=ECSC{is_th1z__go0d_enough__4_you?}'
      - 'FLAG_IN_ENV=true'
