services:
  battleship:
    image: cybersecnatlab/challenge-jail@sha256:245f0de5bf5f9e9030dca9d9450672eea8d39474ea78a7902b93dff60f9060ad
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - "./chall:/home/user/chall:ro"
    ports:
      - "47016:1337"
    environment:
      - "FLAG=ECSC{th1s_g4m3_w4s_n0t_s0_1mp0ss1bl3_r1ght?}"
      - "FLAG_IN_ENV=true"
      - "TIMEOUT=30"
