services:
  yap:
    init: true
    privileged: true
    build:
      context: .
    restart: unless-stopped
    ports:
      - '47015:1337'
    volumes:
      - './chall.py:/home/user/chall:ro'
    environment:
      - 'FLAG=ECSC{y3t_an0th3r_C_pr0gr4m_w1th_1d10t_vulns}'
      - 'TEMPDIRS=/tmp'
      - 'TIMEOUT=30'
